import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "./components/Home/home.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My first next app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <ToastContainer/>
        <div
          className="absolute inset-0 z-0 opacity-[0.15]"
          style={{
            backgroundImage:
              "linear-gradient(#1e293b 1px, transparent 1px), linear-gradient(90deg, #1e293b 1px, transparent 1px)",
            backgroundSize: "45px 45px",
          }}
        ></div>
        <div className="absolute top-0 left-10 w-80 h-80 bg-[#00d1ff]/15 rounded-full filter blur-[120px] animate-blob"></div>
        <div className="absolute bottom-80 right-30 w-80 h-80 bg-purple-500/15 rounded-full filter blur-[120px] animate-blob animation-delay-4000"></div>
        <div>{children}</div>
      </body>
    </html>
  );
}
